### PR TITLE
Add Histogram metric type

### PR DESCRIPTION
**Pull request by brian-brazil**
See https://docs.google.com/document/d/1uSenXRDjDaJLV3qnSD09GqgPdEEDPjER0mVsnGaCYF0/edit#

### CODE REVIEW

**Comment by beorn7** [comment]
:+1: Thanks.

**Comment by beorn7** [comment]
Will work on the Go parts very soon. (client_golang, text parser).

**Comment by grobie** [comment]
:+1:

**Comment by brian-brazil** [comment]
I've got the client_golang text/extraction bits working, just need to finish off the unittests. I haven't touched the metrics in client golang, or the functions in prometheus itself.

**Comment by beorn7** [comment]
@brian-brazil Ah, cool, I'll wait for your text/extraction PR then and work in the exposition parts in the meantime.

**Pull request merged**
