### PR TITLE
add `go_package`, regenerate Go binding file

### PR DESCRIPTION
**Pull request by flier**
When import the `metrics.proto` in a gRPC service definition, the [protoc-gen-go](https://github.com/golang/protobuf) will generate a wrong import path without the [go_package](https://github.com/golang/protobuf#packages-and-input-paths)
```protobuf
syntax = "proto3";
package api;

import "google/protobuf/empty.proto";

import "metrics.proto";

service Host {
    rpc Stats(google.protobuf.Empty) returns (StatsReply) {
        option (google.api.http) = {
            get: "/v1/admin/stats"
        };
    }
}

message StatsReply {
    repeated io.prometheus.client.MetricFamily metrics = 1;
}

```

> 2018/07/10 12:03:45 protoc-gen-go: error:bad Go source code was generated: 120:13: expected type, found '.' (and 4 more errors)
    1	// Code generated by protoc-gen-go. DO NOT EDIT.
    2	// source: api/admin.proto
    3
    4	package api
    5
    6	import proto "github.com/golang/protobuf/proto"
    7	import fmt "fmt"
    8	import math "math"
    9	import  "."

### CODE REVIEW

**Comment by beorn7** [comment]
Thanks. I'll have a look ASAP. In the meantime, you could add the DCO, see https://github.com/probot/dco#how-it-works

**Comment by beorn7** [comment]
@flier which protoc version have you used to regenerate the Go files? I tried 3.3.0 and 3.6.0 and got quite different results each time.

**Comment by flier** [comment]
@beorn7 I use the `protoc` from homebrew, if you prefer to use special `protoc` version, I can regenerate it with your version, I just need the `go_package` in the `metrics.proto` file. :)

```
$ protoc --version
libprotoc 3.6.0

$ brew info protobuf
protobuf: stable 3.6.0 (bottled), HEAD
Protocol buffers (Google's data interchange format)
https://github.com/google/protobuf/
/usr/local/Cellar/protobuf/3.6.0 (256 files, 17.2MB) *
  Poured from bottle on 2018-06-22 at 14:49:31
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/protobuf.rb
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔
Recommended: python@2 ✔
Optional: python ✔
==> Options
--with-python
	Build with python support
--with-test
	Run build-time check
--without-python@2
	Build without python2 support
--HEAD
	Install HEAD version
==> Caveats
Editor support and examples have been installed to:
  /usr/local/opt/protobuf/share/doc/protobuf
```

**Comment by beorn7** [comment]
Weirdly, I have used 3.6.0, too (the newest released version), and still the output differs quite a lot.
Perhaps the homebrew version is compiled with different flags than the binary provided by Google for Linux?

Anyway, I'll just merge this and then regenerate the go code again so that I don't flip back and forth during my own development.

**Comment by flier** [comment]
Thanks, the pre-generated code will fine, because I always regenerate it on the building :)

**Pull request merged**
