### PR TITLE
Rename metrics.proto to io_prometheus_client_metrics.proto

### LINKED ISSUE #44: rename metrics.proto
I was testing apache beam with our source (which uses prometheus) and ran into this problem:

```
panic: proto: file "metrics.proto" is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x15b7a18, 0xc00039d340, 0x1590780, 0xc0003a5ec0, 0xc00039d340)
	/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:54 +0x25f
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc000118540, 0x15bbcb8, 0xc00039d340, 0x0, 0x0)
	/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:128 +0xc58
google.golang.org/protobuf/internal/filedesc.Builder.Build(0x0, 0x0, 0xc0000fea00, 0x659, 0x700, 0xb00000001, 0x0, 0x159d4c0, 0xc00011c3c0, 0x15a93d0, ...)
	/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.26.0/internal/filedesc/build.go:113 +0x1aa
github.com/golang/protobuf/proto.RegisterFile(0x13f2f8b, 0xd, 0x1d4f600, 0x299, 0x299)
	/home/matthew/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/registry.go:48 +0x148
github.com/prometheus/client_model/go.init.1()
	/home/matthew/go/pkg/mod/github.com/prometheus/client_model@v0.2.0/go/metrics.pb.go:677 +0x5a
```

The problem as has been explained to me in the protobuf gophers slack is that all protobuf file names must be globally unique. Any chance this proto file name can be changed or something unlikely to conflict?

See https://gophers.slack.com/archives/C0FSEE1UJ/p1622473569090000 for details.

### PR DESCRIPTION
**Pull request by beorn7**
This should solve naming collision problems, apparently caused by
having a very generically named file directly in the root directory of
the repository.

Fixes #44 (which also provides more context).

@newhook does this solve the problem you ran into?

@bwplotka @kakkoyun please review as this repo is only used by prometheus/client_golang. I believe in the way I changed things here, client_golang shouldn't notice any difference.

### CODE REVIEW

**Comment by newhook** [comment]
I believe it will solve the issue. Thanks!

**Review by bwplotka — APPROVED** [review]
Thanks, it's weird some systems depends on it, but no harm on our side. Never heard about the requirements for proto file name... Lgtm!

**Comment by bwplotka** [comment]
So I talked to people and looks like this might be technically a "breaking change" if someone imports this file directly (it copies that manually, use bazel etc), I think we might want to at least note it in the CHANGELOG.

image

Source: https://bufbuild.slack.com/archives/CRZ680FUH/p1623089122150800 

cc @kakkoyun @beorn7

**Comment by bufdev** [comment]
If you're going to do this, it would be way nicer to do this as `io/prometheus/client/client.proto` - then, if people have `github.com/prometheus/client_model` vendored, they could do `import "io/prometheus/client/client.proto";`, which is just as unlikely to cause a collision. https://docs.buf.build/lint-rules#file_layout

**Comment by bufdev** [comment]
`io/prometheus/client/metric.proto` would be fine as well - the general point being that the file is within a directory structure that matches the package (a rule that exists partially for the issues being seen here).

**Comment by beorn7** [comment]
I understood the conversation linked in #44 such that the file name itself must be unique, too. But I'll do whatever the protobuf experts agree on.

WRT CHANGELOG and breaking changes: There is no CHANGELOG. This repo isn't really versioned, and it is supposed to be used only by prometheus/client_golang and prometheus/pushgateway. I would be surprised if there is a relevant number of people importing the metrics.proto file. (I would actually be genuinely interested in their use case.)

**Comment by bufdev** [comment]
The filename doesn't need to be unique, the path to it does. So `io/prometheus/client/metrics.proto` is just as "unique" as `io_prometheus_client_metrics.proto`, and is better for a host of other reasons as well.

**Comment by bwplotka** [comment]
Oh, thanks @beorn7 I somehow thought we are in client_golang space 🙈 

> The filename doesn't need to be unique, the path to it does. So io/prometheus/client/metrics.proto is just as "unique" as io_prometheus_client_metrics.proto, and is better for a host of other reasons as well.

right, so we could just change the path we store it in?

**Comment by bufdev** [comment]
Everyone will be a lot happier if we just `mkdir -p io/prometheus/client && mv io_prometheus_client_metrics.proto io/prometheus/client/metrics.proto` - at Buf, we actually have an internal issue concerning this exact repo on this problem, as the current setup causes issues with Envoy

**Comment by bufdev** [comment]
>WRT CHANGELOG and breaking changes: There is no CHANGELOG. This repo isn't really versioned, and it is supposed to be used only by prometheus/client_golang and prometheus/pushgateway. I would be surprised if there is a relevant number of people importing the metrics.proto file. (I would actually be genuinely interested in their use case.)

Envoy imports this file in a ton of places

**Comment by beorn7** [comment]
@bufdev I'm just following instructions of others here. Could you create a PR for this repo, which we can then feed to those that told me I have to pick a unique name? We can then see what arguments they present, or if it all turns out to be a misunderstanding.

> Envoy imports this file in a ton of places

Could you give me a tl;dr version why? Is this for Prometheus instrumentation without using an instrumentation library?

**Comment by bufdev** [comment]
I put up https://github.com/prometheus/client_model/pull/46 to try to help with this.

I don't work on the envoy team, but they have a lot of uses of this - just do a simple grep of `metrics.proto` in https://github.com/envoyproxy/envoy

**Comment by beorn7** [comment]
Interesting… they mostly seem to embed Prometheus metrics in other proto messages for their gRPC stuff.

And thanks for #46.

**Pull request merged**
